import test from 'node:test';
import assert from 'node:assert/strict';
import {createMatch,updateBall,DT,passBall} from '../src/match/engine.mjs';
import {teamPlan,actionOptions,attackingCues,shootingCues} from '../src/match/strategy.mjs';
function clear(){const s=createMatch();s.time=2;s.phase='playing';for(const p of s.players){if(p.role!=='GK'){p.x=25;p.z=-25;}}Object.assign(s.ball,{owner:null,x:0,z:0,y:.11,vx:0,vy:0,vz:0,lockUntil:0});return s;}
for(const team of [0,1])test(`team ${team} controls a low pass from 3 m away`,()=>{const s=clear(),p=s.players.find(p=>p.team===team&&p.role==='CM');p.x=3;p.z=0;s.ball.vz=24;updateBall(s,DT);assert.equal(s.ball.owner,p.id);assert.equal(s.ball.vz,0);});
test('the nearest player wins a contested loose ball regardless of team ordering',()=>{const s=clear();Object.assign(s.players[6],{x:1.2,z:0});Object.assign(s.players[17],{x:.9,z:0});updateBall(s,DT);assert.equal(s.ball.owner,'j7');});
test('loose-ball control excludes high balls, fast shots, cooldown and distant players',()=>{for(const kind of ['high','shot','cooldown','distance']){const s=clear(),p=s.players[6];p.x=1.2;p.z=0;if(kind==='high')s.ball.y=2;if(kind==='shot'){s.ball.shot={team:1};s.ball.vz=25;}if(kind==='cooldown')p.cooldown=.5;if(kind==='distance')p.x=3.01;updateBall(s,DT);assert.equal(s.ball.owner,null,kind);}});
test('the control radius does not steal a ball held by an opponent or extend keeper reach',()=>{const s=clear();Object.assign(s.players[6],{x:0,z:0});Object.assign(s.players[17],{x:.9,z:0});s.ball.owner='j7';updateBall(s,DT);assert.equal(s.ball.owner,'j7');const t=clear();t.ball.x=1.3;t.ball.z=t.players[0].z;updateBall(t,DT);assert.equal(t.ball.owner,null);});
test('Possession offers a drive into free space, with a bounded running command',()=>{const s=clear(),p=s.players[20];p.x=0;p.z=12;s.ball.owner=p.id;s.ball.x=0;s.ball.z=12;assert(attackingCues(s,p).canAdvance);const c=actionOptions(s,p).drive_goal;assert(c);assert(c.z>p.z);assert(c.continuous);assert(c.duration<=.65);assert(!shootingCues(s,p).clearShot);});
test('a defender in the running lane removes the open-space drive',()=>{const s=clear(),p=s.players[20];p.x=0;p.z=12;s.ball.owner=p.id;Object.assign(s.players[6],{x:0,z:17});assert(!attackingCues(s,p).canAdvance);assert(!actionOptions(s,p).drive_goal);});
test('strikers and wingers get advancing targets under Possession',()=>{const s=createMatch(),owner=s.players[17];owner.z=15;s.ball.owner=owner.id;s.ball.z=15;const plan=teamPlan(s,1);for(const id of ['j10','j11','j6','j9']){const p=s.players.find(p=>p.id===id);assert(plan.targets[id].z>15);assert(plan.runners.includes(id));assert(actionOptions(s,p,plan).run_attack);}assert(!plan.runners.includes('j3'));assert(plan.targets.j3.z<s.ball.z);});
test('the last passer is marked so an unneeded return pass can be avoided',()=>{const s=createMatch();s.time=2;const a=s.players[20],b=s.players[21];a.x=0;a.z=15;b.x=5;b.z=18;s.ball.owner=a.id;assert(passBall(s,a,b.id));s.ball.owner=b.id;s.ball.ownedAt=s.time;const options=actionOptions(s,b);assert(options.pass_j10);assert.equal(options.pass_j10.returnPass,true);});
