import test from 'node:test';import assert from 'node:assert/strict';
import {createMatch,stepMatch,DT,modelKick,humanPass,humanLob} from '../src/match/engine.mjs';
import {sanitizeTeamState} from '../src/match/decision.mjs';
import {teamStructure,possessionTeam,zoneGap} from '../src/match/team-structure.mjs';
import {buildCoordinatedIntent,buildCoordinatedControls,compileCoordinated,decideCoordinated,movementOptions,kickOptions,forecastKick} from '../src/match/coordinated-control.mjs';
import {readChoice} from '../src/match/model-control.mjs';import {applyTeamResponse} from '../src/match/control.mjs';
const answers=(questions,pick={})=>({answers:Object.fromEntries(Object.entries(questions).map(([id,q])=>{const choice=pick[id]||Object.keys(q.criteria)[0];return [id,{type:'choice',choice,confidence:1,probabilities:Object.fromEntries(Object.keys(q.criteria).map(k=>[k,k===choice?1:0]))}];}))});
function fixture(team=1){const s=createMatch();s.time=2;s.phase='playing';s.requestId=1;const p=s.players.find(p=>p.id===(team?'j10':'h10'));p.x=0;p.z=team?12:-12;Object.assign(s.ball,{x:p.x,z:p.z,owner:p.id,lastTouch:team,lockUntil:0});return {s,p};}
function decision(s,id,action='run',choose=options=>Object.keys(options).find(k=>k!=='hold')){const team=s.players.find(p=>p.id===id).team,first=buildCoordinatedIntent(s,team),a=answers(first.body.questions,{['intent_'+id]:action}),intents=Object.fromEntries(Object.entries(first.choices).map(([id,o])=>[id,readChoice(a,'intent_'+id,o)])),second=buildCoordinatedControls(s,intents,team,first.plan),key=choose(second.choices[id]);return compileCoordinated(s,intents,second,answers(second.body.questions,{['control_'+id]:key}),first.plan)[id];}
test('team duties separate cover, width, support, depth, and only one overlapping fullback',()=>{for(const team of [0,1]){const {s}=fixture(team),plan=teamStructure(s,team),jobs=Object.values(plan.assignments);assert.equal(jobs.filter(j=>j.duty==='cover').length,4);assert.equal(jobs.filter(j=>j.duty==='overlap').length,1);assert.equal(jobs.filter(j=>j.duty==='wide').length,2);assert.equal(plan.presser,null);assert.equal(jobs.length,10);}});
test('defence has one named AI presser and keeps it while another player is only slightly closer',()=>{const {s}=fixture(0);Object.assign(s.players[17],{x:0,z:-10,currentCommand:{assignment:'press',remaining:1}});Object.assign(s.players[18],{x:0,z:-11});const plan=teamStructure(s,1);assert.equal(plan.presser,'j7');assert.equal(Object.values(plan.assignments).filter(j=>j.duty==='press').length,1);});
test('passes into space preserve attacking roles until the flight window ends or opponents gain possession',()=>{const {s}=fixture();Object.assign(s.ball,{owner:null,receiver:null,lastPassFrom:'j10',lastPassAt:s.time,lastTouch:1,kickStyle:'lob',vz:14});assert.equal(possessionTeam(s),1);assert.equal(teamStructure(s,1).phase,'attack');s.ball.owner='h7';assert.equal(possessionTeam(s),0);s.ball.owner=null;s.time+=3;assert.equal(possessionTeam(s),null);});
test('recovery routes move into the assigned area; cover cannot independently become a forward attack',()=>{const {s}=fixture(),plan=teamStructure(s,1);for(const p of s.players.filter(p=>p.team===1&&p.role!=='GK'&&p.id!==s.ball.owner)){const job=plan.assignments[p.id],before=zoneGap(p,job.zone),options=movementOptions(s,p,job);for(const c of Object.values(options).map(o=>o.value).filter(c=>!c.hold)){const next={x:p.x+c.runDirection.x*c.distance,z:p.z+c.runDirection.z*c.distance};assert(zoneGap(next,job.zone)<=Math.max(.5,before-.1));assert([3,5.5,7.5,8.5].includes(c.speed));}}});
test('team 0 requests exclude the human; current controls are visible without sending old probability tables',()=>{const {s}=fixture(0);s.players[6].currentCommand={type:'move',assignment:'cover',x:-6,z:8,speed:5.5,angleDegrees:180,remaining:.7};const sanitized=sanitizeTeamState(s),r=buildCoordinatedIntent(sanitized,0);assert.equal(Object.keys(r.choices).length,9);assert(!r.choices[s.selected]);assert.equal(r.body.state.players.find(p=>p.id==='h7').currentCommand.assignment,'cover');});
test('a delayed forward route starts at receipt and never runs back to the old observation position',()=>{const {s,p}=fixture();for(const q of s.players.filter(q=>q.team===0&&q.role!=='GK')){q.x=26;q.z=-15;}p.z=0;s.ball.z=0;const old=structuredClone(s),d=decision(old,p.id,'run',o=>Object.keys(o).find(k=>k==='dir_0_m_2_s_5.5'));s.orders[p.id]={command:{type:'move',x:0,z:16,speed:6,continuous:true,controlVersion:2,requiresBall:true},expires:s.time+1.2,source:'JEV'};for(let i=0;i<72;i++)stepMatch(s,DT);const before=p.z;assert(before>3);const accepted=applyTeamResponse(s,{[p.id]:d},old,600)[p.id];assert(accepted.applied);assert(Math.abs(accepted.command.z-before-2)<1e-8);for(let i=0;i<24;i++){stepMatch(s,DT);assert(p.vz>=0);}assert(p.z>before);});
test('identical runs preserve velocity while replies arrive; stopping still occurs without replies',()=>{const {s,p}=fixture();for(let k=0;k<4;k++){const d=decision(s,p.id,'run',o=>Object.keys(o).find(k=>k==='dir_0_m_8_s_5.5'));applyTeamResponse(s,{[p.id]:d},structuredClone(s),400);for(let i=0;i<60;i++){stepMatch(s,DT);if(k>0)assert(p.vz>5.4);}}for(let i=0;i<250;i++)stepMatch(s,DT);assert(Math.abs(p.vz)<.01);});
test('a possession change rejects a former attacking command, without controlling the human',()=>{const {s}=fixture(),d=decision(s,'j7'),old=structuredClone(s);s.ball.owner='h10';assert.equal(applyTeamResponse(s,{j7:d},old,200).j7.reason,'Team possession changed');assert.equal(applyTeamResponse(s,{h10:d},old,200).h10.reason,'Human-controlled player');});
test('each kick menu selects aim, speed and elevation together; shots fit under the bar in free flight',()=>{const {s,p}=fixture();p.z=38;s.ball.z=38;for(const flight of [undefined,'chip']){const options=kickOptions(s,p,{type:'shoot',flight});assert(Object.keys(options).length>1);for(const o of Object.values(options)){assert(o.value.forecast.height<=2.15);assert(o.value.forecast.time<=2.2);assert(Number.isFinite(o.value.kickSpeed));assert(Number.isFinite(o.value.elevationDegrees));}}});
test('lob options reach receiving height after an airborne arc; selected physics is applied exactly',()=>{const {s,p}=fixture();Object.assign(s.players[21],{x:9,z:28});const d=decision(s,p.id,'lob_j11');assert(d.command.forecast.apex>=1.6);assert(d.command.forecast.height<=1);assert(modelKick(s,p,d.command));assert(Math.abs(Math.hypot(s.ball.vx,s.ball.vy,s.ball.vz)-d.command.kickSpeed)<1e-8);assert(Math.abs(s.ball.vy-d.command.kickSpeed*Math.sin(d.command.elevationDegrees*Math.PI/180))<1e-8);});
test('coordinated calls use only two stages and one complete-control question per moving player',async()=>{const {s}=fixture(),calls=[];const r=await decideCoordinated(s,async body=>{calls.push(body);return answers(body.questions,calls.length===1?Object.fromEntries(Object.keys(body.questions).map(k=>[k,'run'])):{});});assert.equal(calls.length,2);assert.equal(Object.keys(calls[1].questions).length,10);assert.equal(r.controlVersion,3);assert(r.decisions.j2.parameters.movement);});
test('invalid complete controls reject the batch; cancellation prevents the second model call',async()=>{const {s}=fixture();let count=0;const controller=new AbortController();await assert.rejects(decideCoordinated(s,async body=>{count++;controller.abort();return answers(body.questions);},{signal:controller.signal}));assert.equal(count,1);await assert.rejects(decideCoordinated(s,async body=>{const data=answers(body.questions,Object.fromEntries(Object.keys(body.questions).filter(k=>k.startsWith('intent_')).map(k=>[k,'run'])));if(Object.keys(body.questions)[0].startsWith('control_'))data.answers[Object.keys(body.questions)[0]].choice='invalid';return data;}));});

test('human ground passes and lobs into space keep teammate support active',()=>{for(const kick of [humanPass,humanLob]){const {s,p}=fixture(0);for(const q of s.players.filter(q=>q.id!==p.id)){q.x=25;q.z=30;}assert(kick(s,{x:-1,z:0},.5));assert.equal(s.ball.receiver,null);assert.equal(s.ball.lastPassFrom,p.id);assert.equal(possessionTeam(s),0);assert.equal(teamStructure(s,0).phase,'attack');}});
test('a named AI receiver gets a receiving area while the remaining team keeps its shape',()=>{const {s}=fixture();Object.assign(s.ball,{owner:null,lastTouch:1,lastPassFrom:'j10',lastPassAt:s.time,kickStyle:'pass',receiver:'j11',passTarget:{x:8,z:18}});const plan=teamStructure(s,1);assert.equal(plan.assignments.j11.duty,'receive');assert.deepEqual(plan.assignments.j11.centre,{x:8,z:18});assert.equal(plan.assignments.j3.duty,'cover');});
