import test from 'node:test';import assert from 'node:assert/strict';
import {createMatch,stepMatch,DT} from '../src/match/engine.mjs';
import {buildCoordinatedIntent,buildCoordinatedControls,compileCoordinated,movementOptions} from '../src/match/coordinated-control.mjs';
import {readChoice} from '../src/match/model-control.mjs';import {applyTeamResponse} from '../src/match/control.mjs';
function fixture(team=1){const s=createMatch();s.time=2;s.phase='playing';for(const p of s.players.filter(p=>p.role!=='GK')){p.x=25;p.z=30;}const carrier=s.players.find(p=>p.id===(team?'h10':'j10')),defender=s.players.find(p=>p.id===(team?'j7':'h7'));Object.assign(carrier,{x:0,z:0});Object.assign(defender,{x:0,z:team?7:-7});Object.assign(s.ball,{owner:carrier.id,x:0,z:0,lastTouch:carrier.team,lockUntil:0});s.controlOwner=carrier.id;return {s,carrier,defender};}
const answers=(questions,picks={})=>({answers:Object.fromEntries(Object.entries(questions).map(([id,q])=>{const choice=picks[id]||Object.keys(q.criteria)[0];return [id,{type:'choice',choice,confidence:1,probabilities:Object.fromEntries(Object.keys(q.criteria).map(k=>[k,k===choice?1:0]))}];}))});
function challenge(s,p,action='press_tackle'){const first=buildCoordinatedIntent(s,p.team),a=answers(first.body.questions,{['intent_'+p.id]:action}),intents=Object.fromEntries(Object.entries(first.choices).map(([id,o])=>[id,readChoice(a,'intent_'+id,o)])),second=buildCoordinatedControls(s,intents,p.team,first.plan),key=Object.keys(second.choices[p.id]).find(k=>k===`dir_${p.z>0?8:0}_m_8_s_8.5`);assert(key);return compileCoordinated(s,intents,second,answers(second.body.questions,{['control_'+p.id]:key}),first.plan)[p.id];}
test('only the assigned presser gets a close-and-tackle choice outside immediate reach',()=>{const {s,defender}=fixture(),r=buildCoordinatedIntent(s);assert(r.choices[defender.id].press_tackle);assert(!r.choices[defender.id].tackle);assert.equal(Object.values(r.choices).filter(o=>o.press_tackle).length,1);});
for(const team of [0,1])test(`team ${team} follows a model-selected approach and tackles once without a second model reply`,()=>{const {s,carrier,defender}=fixture(team),d=challenge(s,defender);assert(applyTeamResponse(s,{[defender.id]:d},structuredClone(s),450)[defender.id].applied);for(let i=0;i<20;i++)stepMatch(s,DT);assert.equal(s.ball.owner,carrier.id);assert.equal(defender.cooldown,0);for(let i=0;i<110;i++)stepMatch(s,DT);assert.equal(s.ball.owner,defender.id);assert.equal(s.stats[team].tackles,1);});
test('a plain run does not tackle automatically',()=>{const {s,carrier,defender}=fixture(),d=challenge(s,defender,'run');applyTeamResponse(s,{[defender.id]:d},structuredClone(s),450);for(let i=0;i<135;i++)stepMatch(s,DT);assert.equal(s.ball.owner,carrier.id);assert.equal(s.stats[1].tackles,0);});
test('an old challenge cannot tackle a different carrier after a pass',()=>{const {s,defender}=fixture(),d=challenge(s,defender),old=structuredClone(s);s.ball.owner='h8';assert.equal(applyTeamResponse(s,{[defender.id]:d},old,300)[defender.id].reason,'Ball carrier changed');});
test('cooldown removes tackle choices and the human player is never assigned an AI challenge',()=>{const {s,defender}=fixture();defender.cooldown=.5;const r=buildCoordinatedIntent(s);assert(!r.choices[defender.id].press_tackle);assert(!buildCoordinatedIntent(s,0).choices[s.selected]);});
test('near-carrier approach choices include sub-metre routes and target the carrier body',()=>{const {s,defender}=fixture();defender.z=1.9;s.ball.z=-.64;const first=buildCoordinatedIntent(s),a=answers(first.body.questions,{intent_j7:'press_tackle'}),intents=Object.fromEntries(Object.entries(first.choices).map(([id,o])=>[id,readChoice(a,'intent_'+id,o)])),second=buildCoordinatedControls(s,intents,1,first.plan);assert.equal(first.plan.assignments.j7.centre.z,0);assert(Object.values(second.choices.j7).some(o=>o.value.distance<1));});

test('chasing a 5.8 m/s carrier offers sustained routes with speeds that close the gap',()=>{const {s,carrier,defender}=fixture();carrier.vz=-5.8;const plan=buildCoordinatedIntent(s).plan,options=movementOptions(s,defender,plan.assignments[defender.id],true);const routes=Object.values(options).map(o=>o.value).filter(c=>!c.hold);assert(routes.length>1);assert(routes.some(c=>c.speed===7.5));assert(routes.some(c=>c.speed===8.5));for(const c of routes){assert(c.distance>=8);assert(c.speed>=7.5);assert(c.runDirection.z<0);}});

test('pressing follows the carrier to the touchline and goal line instead of stopping at formation bounds',()=>{const {s,carrier,defender}=fixture();Object.assign(carrier,{x:33,z:51.5,vx:0,vz:5.8});Object.assign(defender,{x:33,z:47});Object.assign(s.ball,{x:33,z:51.5});const plan=buildCoordinatedIntent(s).plan,job=plan.assignments[defender.id];assert(job.centre.x>32);assert(job.centre.z>51);const routes=Object.values(movementOptions(s,defender,job,true)).map(o=>o.value).filter(c=>!c.hold);assert(routes.length>0);assert(routes.some(c=>c.runDirection.z>0));});
