import test from 'node:test';import assert from 'node:assert/strict';
import {createMatch,selectHumanPlayer,stepMatch,updateBall,DT,humanPass,humanLob,humanChip,modelKick} from '../src/match/engine.mjs';
import {buildIntentRequest,readIntents,buildParameterRequest,compileModelCommands,decideModelControl} from '../src/match/model-control.mjs';
import {sanitizeTeamState} from '../src/match/decision.mjs';import {applyTeamResponse} from '../src/match/control.mjs';import {supportObservation} from '../src/match/support.mjs';
function fixture(){const s=createMatch();s.phase='playing';s.time=1;s.requestId=1;for(const p of s.players)if(p.role!=='GK'){p.x=28;p.z=35;}const p=s.players.find(p=>p.id===s.selected);p.x=0;p.z=0;p.heading=Math.PI;s.ball.owner=p.id;s.ball.x=0;s.ball.z=0;s.ball.lockUntil=0;return {s,p};}
function answers(questions,select={}){return {answers:Object.fromEntries(Object.entries(questions).map(([id,q])=>{const choice=select[id]||Object.keys(q.criteria)[0];return [id,{type:'choice',choice,confidence:1,probabilities:Object.fromEntries(Object.keys(q.criteria).map(k=>[k,k===choice?1:0]))}];}))};}
function order(){return {action:'support',command:{type:'move',controlVersion:2,requiresBall:false,continuous:true,x:-8,z:-12,speed:6,duration:1.2,label:'Offer a passing option'}};}
test('teammate requests contain nine players and exclude the selected player and both keepers',()=>{const {s}=fixture();for(const id of ['h10','h7','h2']){selectHumanPlayer(s,id);const r=buildIntentRequest(s,false,0);assert.equal(Object.keys(r.choices).length,9);assert(!r.choices[id]);assert(Object.keys(r.choices).every(k=>k.startsWith('h')&&k!=='h1'));assert.equal(r.body.state.humanControlled,id);}assert.equal(Object.keys(buildIntentRequest(s).choices).length,10);});
test('invalid human selections cannot enter the endpoint',()=>{const {s}=fixture();for(const selected of ['h1','j10','bad'])assert.throws(()=>sanitizeTeamState({...s,selected}));});
test('selected human cannot receive or execute a model command',()=>{const {s,p}=fixture(),d=order();d.command.requiresBall=true;assert.equal(applyTeamResponse(s,{[p.id]:d},structuredClone(s),100)[p.id].applied,false);s.orders[p.id]={command:d.command,expires:4};for(let i=0;i<30;i++)stepMatch(s,DT);assert.equal(p.x,0);assert.equal(p.z,0);assert.equal(p.executing.source,'Human');assert(!s.orders[p.id]);});
test('a switch clears both affected players and rejects replies from the previous selection',()=>{const {s}=fixture(),old=structuredClone(s);s.orders.h7={command:order().command};s.orders.h10={command:order().command};selectHumanPlayer(s,'h7');assert(!s.orders.h7&&!s.orders.h10);assert.equal(applyTeamResponse(s,{h8:order()},old,100).h8.reason,'Human selection changed');});
test('live teammates move only from JEV commands; the selected player follows input',()=>{const {s,p}=fixture(),q=s.players.find(p=>p.id==='h7');q.x=8;q.z=0;applyTeamResponse(s,{h7:order()},structuredClone(s),200);for(let i=0;i<30;i++)stepMatch(s,DT,{x:1});assert(q.x<8&&q.z<0);assert.equal(q.executing.source,'JEV');assert(p.x>0);assert.equal(p.executing.source,'Human');const idle=s.players.find(p=>p.id==='h6');assert.equal(idle.executing.source,'Waiting');});
test('both teams see support, unmarking, overlap, depth and cover choices in possession',()=>{for(const team of [0,1]){const {s}=fixture();s.ball.owner=team?'j10':'h10';const r=buildIntentRequest(s,false,team);const options=r.choices[team?'j7':'h7'];for(const key of ['support','get_free','overlap','run_behind','cover'])assert(options[key]);assert.equal(r.body.state.support.team,team);}});
test('space observations report marking and open receiving lanes without imposing movement',()=>{const {s}=fixture(),p=s.players.find(p=>p.id==='h7'),q=s.players.find(p=>p.id==='j7');p.x=8;p.z=-5;q.x=8.5;q.z=-5;const info=supportObservation(s,0).players.h7;assert.equal(info.nearestOpponent.id,q.id);assert.equal(info.nearestOpponent.distanceM,.5);assert.equal(info.openSpaces.length,3);assert(info.openSpaces.some(x=>x.nearestOpponentM>3));assert(!('target'in info));});
test('teammate two-stage calls use own-team support context and exact model parameters',async()=>{const {s}=fixture();let n=0;const result=await decideModelControl(s,async body=>{n++;assert.equal(body.state.support.team,0);assert.equal(body.state.humanControlled,s.selected);return answers(body.questions,n===1?{intent_h7:'support'}:{h7_direction:'dir_8',h7_distance:'metres_16',h7_speed:'speed_6'});},{team:0});assert.equal(n,2);assert.equal(Object.keys(result.decisions).length,9);assert.equal(result.decisions.h7.command.purpose,'support');assert.equal(result.decisions.h7.command.speed,6);});
test('lob has an airborne arc and preserves pass statistics and receiver selection',()=>{const {s}=fixture(),receiver=s.players.find(p=>p.id==='h7');receiver.x=0;receiver.z=-20;assert(humanLob(s,{x:0,z:-1},.35));assert.equal(s.ball.kickStyle,'lob');assert.equal(s.ball.receiver,'h7');assert.equal(s.selected,'h7');assert.equal(s.stats[0].passes,1);let apex=0;for(let i=0;i<180;i++){s.time+=DT;updateBall(s,DT);apex=Math.max(apex,s.ball.y);}assert(apex>3);assert.equal(s.stats[0].shots,0);});
test('a lob passes above a defender that intercepts a ground pass',()=>{const owner=[];for(const kick of [humanPass,humanLob]){const {s}=fixture(),defender=s.players.find(p=>p.id==='j7');defender.x=0;defender.z=-7;assert(kick(s,{x:0,z:-1},.4));for(let i=0;i<95;i++){s.time+=DT;updateBall(s,DT);}owner.push(s.ball.owner);if(kick===humanLob)assert(s.ball.y>2);}assert.equal(owner[0],'j7');assert.notEqual(owner[1],'j7');});
test('chip follows the human aim and power and counts as one shot',()=>{for(const power of [0,.5,1]){const {s}=fixture();assert(humanChip(s,{x:1,z:-1},power));assert.equal(s.ball.kickStyle,'chip');assert(s.ball.vx>0&&s.ball.vz<0);assert(Math.abs(Math.hypot(s.ball.vx,s.ball.vy,s.ball.vz)-(9+power*12))<1e-9);assert.equal(s.stats[0].shots,1);assert.equal(s.stats[0].passes,0);assert(s.ball.shot);}});
test('JEV lob and chip intents expose loft controls and preserve selected launch physics',()=>{for(const action of ['lob_h7','chip']){const {s}=fixture();selectHumanPlayer(s,'h8');const first=buildIntentRequest(s,false,0),intents=readIntents(answers(first.body.questions,{intent_h10:action}),first),second=buildParameterRequest(s,intents,false,0);assert(!second.choices.h10.elevation.degrees_0);const data=answers(second.body.questions,{h10_aim:'angle_180',h10_power:'speed_14',h10_elevation:'degrees_40'}),d=compileModelCommands(s,intents,second,data).h10;assert(modelKick(s,s.players.find(p=>p.id==='h10'),d.command));assert.equal(s.ball.kickStyle,action==='chip'?'chip':'lob');assert(Math.abs(s.ball.vy-14*Math.sin(40*Math.PI/180))<1e-9);}});
